services:
  postgresdb:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345612
    volumes:
      - go-pg-data:/var/lib/postgresql/data
  redisdb:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  go-pg-data: